version: '3.8'

networks:
  shiawasedo:
    driver: bridge

volumes:
  sqldata:
    driver: local

services:
  nginx:
    build:
      context: .docker
      dockerfile: nginx/Dockerfile
    container_name: shiawasedo-nginx
    ports:
      - "8080:80"
      - "9001:9001"
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - php
    networks:
      - orderchamp

  php:
    build:
      context: .docker
      dockerfile: php/Dockerfile
    container_name: shiawasedo-php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - shiawasedo

  mysql:
      image: mysql
      ports:
          - "3306:3306"
      environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USERNAME}
      container_name: shiawasedo-mysql
      networks:
          - shiawasedo
      volumes:
          - ./mysqldata:/var/lib/mysql
